sudo: false
language: c++

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libasound2-dev
      - libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
