sudo: required
dist: trusty
language: cpp

addons:
  apt:
    packages:
      - cmake
      - libasound2-dev
      - libboost-all-dev

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

