sudo: required
dist: trusty
language: cpp
compiler: g++

addons:
  apt:
    packages:
      - cmake
      - libasound2-dev
      - libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
